- pipeline:
    name: check
    description: |
      Newly opened pull requests enter this pipeline to receive an
      initial verification
    manager: independent
    trigger:
      github1:
        - event: pull_request
          action:
            - opened
            - changed
            - reopened
        - event: pull_request
          action: comment
          comment: (?i)^\s*recheck\s*$
    start:
      github1:
        status: pending
        comment: false
    success:
      github1:
        status: 'success'
    failure:
      github1:
        status: 'failure'

- project:
    name: devops-zuul/zuul-test-config
    check:
      jobs:
        - noop


- job:
    name: base
    parent: null
