- pipeline:
    name: check
    post-review: true
    description: This pipeline runs jobs whenever we proposed changes and commit on git
    manager: independent
    precedence: low
    trigger:
      github:
        - event: push
          ref: ^refs/heads/.*$
    success:
      github:
        status: 'success'
        merge: true
        comment: true
     
    failure:
      github:
        status: 'failure'
        comment: true
- pipeline:
    name: gate
    description: |
      Newly uploaded patchsets enter this pipeline to receive an
      initial status. Changes that have been approved by core developers are enqueued
      in order in this pipeline, and if they pass tests, will be
      merged.
    manager: independent
    trigger:
      github:
        - event: pull_request
          action:
            - opened
            - changed
            - reopened
        - event: pull_request
          action: comment
          comment: (?i)^\s*recheck\s*$
    start:
      github:
        status: 'pending'
        status-url: "http://localhost:9000/t/quickstart/status"
        comment: false
    success:
      github:
        status: 'success'
     
    failure:
      github:
        status: 'failure'


   
- project:
    name: devops-zuul/zuul-test-config
    check:
      jobs:
        - noop


- job:
    name: base
    parent: null
    pre-run: base-playbook.yaml
    
