- hosts: all
  tasks:
    - name: Start zuul_console daemon.
      zuul_console:

- hosts: localhost
  tasks:
    - zuul_return:
        data:
          zuul:
            log_url: "http://localhost:8000"
